# Generated by Django 5.1.1 on 2024-09-14 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'First Name must be at least 3 characters')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Last Name must be at least 3 characters')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator('This is not a valid email.')])),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4, 'Please enter a valid address.')])),
                ('nic', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10, 'Please enter a valid NIC address.')])),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='employees/')),
            ],
        ),
    ]
