# Generated by Django 5.1.1 on 2024-09-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='uploads/users/')),
            ],
        ),
    ]
